name: AVDBS multi-board media bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [t22, t50]   # 원하는 게시판 추가 가능
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run AVDBS crawler
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AVDBS_BASE: "https://www.avdbs.com"
          AVDBS_BOARD_PATH: "/board/${{ matrix.board }}"
          AVDBS_COOKIE: ${{ secrets.AVDBS_COOKIE }}
        run: python -u main_avdbs.py

      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state/ || true
            git commit -m "update seen (${matrix.board})" || true
            git pull --rebase || true
            git push || true
          fi
